"""
Credit Risk Monte Carlo Project
Thesis:
Gaussian Vasicek-style credit portfolio models may underestimate tail risk and capital buffers
because they underrepresent extreme macro shocks and joint default clustering. This script starts
with a baseline Vasicek Monte Carlo model, then compares it to a fat-tailed Student-t factor model.

Core outputs:
- Expected Loss (EL)
- VaR at 99% and 99.9%
- Expected Shortfall / CVaR at 99% and 99.9%
- Implied unexpected-loss capital buffer = VaR_99.9 - EL
"""

import numpy as np
import pandas as pd
from scipy.stats import norm, t
import matplotlib.pyplot as plt


# ============================================================
# 1. Global parameters
# ============================================================

np.random.seed(42)

# Portfolio assumptions
N_BORROWERS = 1000
N_SIMULATIONS = 100_000

PD = 0.02          # annual probability of default: 2%
LGD = 0.45         # loss given default: 45%
EAD = 1_000_000    # exposure at default per borrower
RHO = 0.15         # asset correlation / systematic factor loading

# Student-t assumptions
T_DF = 4           # degrees of freedom; lower df = fatter tails

# Risk levels
ALPHAS = [0.99, 0.999]

# ============================================================
# 2. Helper functions
# ============================================================

def calculate_risk_metrics(losses, alphas=ALPHAS):
    """
    Calculate EL, VaR, ES, and capital buffer from simulated portfolio losses.

    EL = average loss
    VaR_alpha = alpha quantile of loss distribution
    ES_alpha = average loss conditional on loss > VaR_alpha
    Capital buffer = VaR_99.9 - EL
    """
    losses = np.asarray(losses)
    results = {
        "EL": losses.mean(),
        "Std Loss": losses.std(),
    }

    for alpha in alphas:
        var = np.quantile(losses, alpha)
        es = losses[losses >= var].mean()
        results[f"VaR_{alpha:.1%}"] = var
        results[f"ES_{alpha:.1%}"] = es

    if 0.999 in alphas:
        results["Capital_Buffer_VaR_99.9_minus_EL"] = results["VaR_99.9%"] - results["EL"]

    return results


def simulate_vasicek_gaussian(
    n_borrowers=N_BORROWERS,
    n_simulations=N_SIMULATIONS,
    pd=PD,
    lgd=LGD,
    ead=EAD,
    rho=RHO,
):
    """
    Gaussian Vasicek one-factor model.

    Latent borrower health:
        A_i = sqrt(rho) * Z + sqrt(1-rho) * epsilon_i

    Default rule:
        D_i = 1 if A_i < default_threshold

    Z = systematic macro factor
    epsilon_i = borrower-specific shock
    rho = asset correlation / strength of common macro factor
    """

    # Threshold = z-score corresponding to the probability of default (2%)
    # Reverse engineer z-score formula to look for z instead of probability using norm.ppf
    # Below what threshold of companies' financial health can we expect a default?
    threshold = norm.ppf(pd)

    # Systematic macro shock: one per scenario
    Z = np.random.normal(0, 1, size=n_simulations)

    # Idiosyncratic shocks: one per borrower per scenario
    # Use two arrays of n to create a matrix 
    eps = np.random.normal(0, 1, size=(n_simulations, n_borrowers))

    # Latent asset/financial health
    # "None" transforms 1D list output of Z (Macro Economy) into a matrix shape so that it can be calculated with epsilon (Micro: Idyosincratic Risk)
    asset = np.sqrt(rho) * Z[:, None] + np.sqrt(1 - rho) * eps

    # Default indicator: Bernoulli outcome (Binary: 0 = no default / 1 = default) generated by threshold rule
    # Use astype(int) to convert True/False default output into a Bernoulli (binary) variable
    defaults = (asset < threshold).astype(int)

    # Portfolio loss per scenario
    # borrowers = columns / scenarios = rows, axis=1 --> SUM OF EACH SCENARIO (rows) across all borrowers (columns)
    # axis=0: opposite --> sum up each column across all rows
    losses = defaults.sum(axis=1) * lgd * ead

    return losses



def simulate_student_t_factor(
    n_borrowers=N_BORROWERS,
    n_simulations=N_SIMULATIONS,
    pd=PD,
    lgd=LGD,
    ead=EAD,
    rho=RHO,
    df=T_DF,
):
    """
    Fat-tailed one-factor model using Student-t shocks.

    Main difference vs Gaussian Vasicek:
    - Gaussian factor assumes macro shocks are thin-tailed.
    - Student-t factor gives more probability to extreme macro shocks.

    This creates stronger crisis default clustering and a fatter loss tail.
    """

    # Use t threshold so unconditional default probability is roughly pd under t shocks
    threshold = t.ppf(pd, df=df)

    # Systematic fat-tailed macro shock
    #np.random.normal() and t.rvs() do the same thing — they both generate random samples from a normal distribution
    # MONTE CARLO (Z & eps): simulate many random scenarios
    Z = t.rvs(df=df, size=n_simulations)

    # Idiosyncratic fat-tailed shocks
    eps = t.rvs(df=df, size=(n_simulations, n_borrowers))

    # Standardize t shocks to variance approximately 1 when df > 2
    scale = np.sqrt(df / (df - 2))
    Z = Z / scale
    eps = eps / scale
    threshold = threshold / scale
    
    # MONTE CARLO OUTPUTS
    asset = np.sqrt(rho) * Z[:, None] + np.sqrt(1 - rho) * eps
    defaults = (asset < threshold).astype(int)
    losses = defaults.sum(axis=1) * lgd * ead

    return losses

# ============================================================
# 3. Run baseline simulations
# ============================================================

if __name__ == "__main__":
    gaussian_losses = simulate_vasicek_gaussian()
    student_t_losses = simulate_student_t_factor()

    gaussian_metrics = calculate_risk_metrics(gaussian_losses)
    student_t_metrics = calculate_risk_metrics(student_t_losses)

    results = pd.DataFrame(
        [gaussian_metrics, student_t_metrics],
        index=["Gaussian Vasicek", "Student-t Factor"]
    )

    pd.options.display.float_format = "{:,.2f}".format
    print("\nRisk Metrics Comparison")
    print(results)

    # Extra: show default-count intuition
    gaussian_default_counts = gaussian_losses / (LGD * EAD)
    student_t_default_counts = student_t_losses / (LGD * EAD)

    comparison = pd.DataFrame({
        "Gaussian_Defaults": gaussian_default_counts,
        "StudentT_Defaults": student_t_default_counts,
    })

    print("\nDefault Count Summary")
    print(comparison.describe(percentiles=[0.50, 0.90, 0.99, 0.999]))

# ============================================================
# 4. Importance Sampling - Gaussian Vasicek
# ============================================================

def weighted_quantile(values, weights, alpha):
    # Sort losses from smallest to largest
    sorted_index = np.argsort(values)
    sorted_values = values[sorted_index]
    sorted_weights = weights[sorted_index]

    # Cumulative probability using weights
    cumulative_weights = np.cumsum(sorted_weights)
    cutoff = alpha * cumulative_weights[-1]

    return sorted_values[np.searchsorted(cumulative_weights, cutoff)]


def calculate_weighted_risk_metrics(losses, weights, alphas=ALPHAS):
    results = {
        "Weighted_EL": np.sum(weights * losses) / np.sum(weights),
        "Weight_Mean": weights.mean(),
        "Weight_Std": weights.std(),
    }

    for alpha in alphas:
        var = weighted_quantile(losses, weights, alpha)

        tail = losses >= var
        es = np.sum(weights[tail] * losses[tail]) / np.sum(weights[tail])

        results[f"Weighted_VaR_{alpha:.1%}"] = var
        results[f"Weighted_ES_{alpha:.1%}"] = es

    results["Weighted_Capital_Buffer_VaR_99.9_minus_EL"] = (
        results["Weighted_VaR_99.9%"] - results["Weighted_EL"]
    )

    return results


# Importance Sampling shifts the mean of the sampling distribution, but the shape (normal) remains
# Why shift to the left when extreme losses are to the right of the PDF? X-axis on Vasicek Model is not credit losses but MACRO factors (Z)
# Vasicek model focuses on companies' correlation to the MACROECONOMY (Z), shift to the left = focus  on downturn scenarios = greater losses

def simulate_vasicek_importance_sampling(mu_shift=-2.0):
    threshold = norm.ppf(PD)

    # Shift macro factor toward crisis
    Z_shifted = np.random.normal(mu_shift, 1, size=N_SIMULATIONS)

    # Company-specific shocks stay normal
    eps = np.random.normal(0, 1, size=(N_SIMULATIONS, N_BORROWERS))

    asset = np.sqrt(RHO) * Z_shifted[:, None] + np.sqrt(1 - RHO) * eps

    defaults = (asset < threshold).astype(int)

    losses = defaults.sum(axis=1) * LGD * EAD

    # Importance sampling weight = original density / shifted density
    weights = norm.pdf(Z_shifted, loc=0, scale=1) / norm.pdf(Z_shifted, loc=mu_shift, scale=1)

    return losses, weights

# Run importance sampling
is_losses, is_weights = simulate_vasicek_importance_sampling(mu_shift=-2.0)

# Check output
print(is_losses[:10])
print(is_weights[:10])

# Output is accurate: we are observing more extreme losses (more tail scenarios), but allocating a lesser weight to keep unbiased results.

# Run importance sampling
is_losses, is_weights = simulate_vasicek_importance_sampling(mu_shift=-2.0)

# 1. Check whether weights behave correctly
weight_check = pd.Series(is_weights).describe(percentiles=[0.01, 0.05, 0.50, 0.95, 0.99])

print("\nWeight Check")
print(weight_check)

print("\nMean weight should be close to 1:")
print(is_weights.mean())

is_metrics = calculate_weighted_risk_metrics(is_losses, is_weights)

is_results = pd.DataFrame(
    [is_metrics],
    index=["Gaussian Vasicek + Importance Sampling"]
)

print("\nImportance Sampling Results")
print(is_results)

# STABILITY TEST
# 2. Compare standard MC vs Importance Sampling stability

seeds = range(30)

mc_vars = []
is_vars = []

for seed in seeds:
    np.random.seed(seed)

    # Standard MC
    mc_losses = simulate_vasicek_gaussian()
    mc_var_999 = np.quantile(mc_losses, 0.999)
    mc_vars.append(mc_var_999)

    # Importance Sampling
    is_losses, is_weights = simulate_vasicek_importance_sampling(mu_shift=-2.0)
    is_var_999 = weighted_quantile(is_losses, is_weights, 0.999)
    is_vars.append(is_var_999)

stability = pd.DataFrame({
    "Standard_MC_VaR_99.9": mc_vars,
    "Importance_Sampling_VaR_99.9": is_vars
})

print("\nVaR Stability Across Seeds")
print(stability.describe())

plt.figure(figsize=(10,5))

plt.plot(mc_vars, marker='o', label='Standard MC VaR 99.9%')
plt.plot(is_vars, marker='o', label='Importance Sampling VaR 99.9%')

plt.title("VaR Stability Across Seeds")
plt.xlabel("Simulation Run (Seed)")
plt.ylabel("VaR 99.9%")

plt.legend()
plt.grid(True)

plt.show()
